let calculator={calcDataset:{rspSender:"",rspRecipient:"",townSender:"",townRecipient:"",weight:"",height:"",width:"",length:"",declaredCost:"",volumeGeneral:"",cargoType:"",seatsAmount:1},recipientUserDataset:{description:"",phone:"",address:"",town:""},senderUserDataset:{description:"",phone:"",address:"",town:""},nngDataset:{date:"",additionalInformation:"",},errors:{},init:function(params){calculator.api=params.api;if(params.mode===undefined){mode="study";}
if(params.mode=="study"){calculator.url=calculator.api.study.url;calculator.key=calculator.api.study.key;}else{calculator.url=calculator.api.openws.url;calculator.key=calculator.api.openws.key;}
if(params.lang===undefined){calculator.lang="ru";}else{calculator.lang=params.lang;}
calculator.initCargoType();calculator.searchCity();calculator.getAdditionalServices();calculator.getDepartureConditions();calculator.getDeliveryConditions();calculator.initCalendar();calculator.place();calculator.cubeParams();calculator.otherParams();calculator.acivateCityPoint();calculator.reverseAB();calculator.userSet();$('a#calculate').click(function(){calculator.calculate();return false;});$('a#order').click(function(){calculator.order();return false;});$('#tracking').keyup(function(e){if(e.keyCode==13){var num=$(this).val();calculator.tracking(num);}});$('#search_tracking').click(function(e){var num=$('input#tracking').val();calculator.tracking(num);return false;});},setCache:function(key,data,time){if('localStorage'in window&&window['localStorage']!==null){var cachedData=lscache.get(key);if(cachedData==null){lscache.set(key,data,time);}}else{return null;}},getCache:function(key){if('localStorage'in window&&window['localStorage']!==null){var cachedData=lscache.get(key);if(cachedData!=null){return lscache.get(key);}}else{return null;}},errorPicker:function(errObj){},order:function(){calculator.getCounterparty(calculator.senderUserDataset.description,function(senderResult){if(senderResult!=false){calculator.nngDataset.senderPhone=senderResult.phone;calculator.nngDataset.contactSender=senderResult.ref;calculator.addRecipient();}else{calculator.senderUserDataset.language=calculator.lang;calculator.senderUserDataset.apiKey=calculator.key;var paramsSender=JSON.stringify(calculator.senderUserDataset);$.ajax({type:"POST",url:calculator.url+calculator.api.post.createUser,dataType:"json",data:paramsSender,success:function(senderData){if(senderData.success=="true"){calculator.addRecipient();}
if(senderData.success=="false"){calculator.errorPicker(senderData.error);}}});}});},addRecipient:function(){calculator.getCounterparty(calculator.recipientUserDataset.description,function(recipientResult){if(recipientResult!=false){calculator.nngDataset.recipient=recipientResult.ref;calculator.nngDataset.recipientAddress=recipientResult.address;calculator.nngDataset.recipientPhone=recipientResult.phone;calculator.addNng();}else{calculator.recipientUserDataset.language=calculator.lang;calculator.recipientUserDataset.apiKey=calculator.key;var paramsRecipient=JSON.stringify(calculator.recipientUserDataset);$.ajax({type:"POST",url:calculator.url+calculator.api.post.createUser,data:paramsRecipient,dataType:"json",success:function(dataRecipient){if(dataRecipient.success=="true"){calculator.addNng();}
if(dataRecipient.success=="false"){calculator.errorPicker(dataRecipient.error);}}});}});},addNng:function(){console.log(calculator.nngDataset);console.log(calculator.calcDataset);calculator.nngDataset.apiKey=calculator.key;$.extend(calculator.nngDataset,calculator.calcDataset);var nngParams=JSON.stringify(calculator.nngDataset);$.ajax({type:"POST",url:calculator.url+calculator.api.post.createDocNng+'?apiKey='+calculator.key,data:nngParams,dataType:"json",success:function(dataNng){if(dataNng.success=="true"){var result=dataNng.data;console.log(result);$('.declaration__number').text(result[0]["number"]);}}});},getCounterparty:function(searchString,callback){if(searchString===undefined){searchString="";}
$.ajax({type:"GET",url:calculator.url+calculator.api.get.counterparty,data:{apiKey:calculator.key,language:calculator.lang,searchString:searchString},dataType:"json",success:function(data){var result=data.data;for(var i in result){if(result[i].description==searchString){callback(result[i]);return;}}
callback(false);}});},getDepartments:function(callback,ref){console.time("departments request");if(calculator.getCache('departments')==null){var result='';var data={language:calculator.lang}
if(ref!==undefined){data.ref=ref;}
$.ajax({type:"GET",url:calculator.url+calculator.api.get.getRsp,data:data,dataType:"json",async:false,success:function(data){if(data.success=="true"){result=data.data;}}});calculator.setCache('departments',result,2)}else{result=calculator.getCache('departments');}
departmens_json=JSON.stringify(result);console.timeEnd("departments request");},showRoute:function(num){$.ajax({type:"GET",url:calculator.url+calculator.api.get.nngList,data:{apiKey:calculator.key,number:num},dataType:"json",success:function(data){console.log(data);if(data.success=="true"){var result=data.data[0];var coords={};calculator.getDepartments(result.rspSender,function(department){coords.sender={lat:department.latitude,lng:department.longitude}
calculator.getDepartments(result.rspRecipient,function(department){coords.recipient={lat:department.latitude,lng:department.longitude}
SATmap.Router(coords);})});}
if(data.success=="false"){calculator.errorPicker(data.error);}}});},tracking:function(num){$.ajax({type:"GET",url:calculator.url+calculator.api.get.tracking,data:{apiKey:calculator.key,number:num},dataType:"json",success:function(data){if(data.success=="true"){var result=data.data[0];console.log(data.data[0]);var coords={};coords.sender={lat:result.rspFrom.latitude,lng:result.rspFrom.longitude}
coords.recipient={lat:result.rspTo.latitude,lng:result.rspTo.longitude}
SATmap.Router(coords);for(var i in result){if(i=="type"){var type=result[i].split('-');$('.page__block--tracking #typeFrom').text(type[0]);$('.page__block--tracking #typeTo').text(type[1]);}else{var val=result[i];switch(i){case"rspFrom":val=result.rspFrom.description+", "+result.rspFrom.address;break;case"rspTo":val=result.rspTo.description+", "+result.rspTo.address;break;case"payData":val=result.payData["sum"];break;}
$('.page__block--tracking #'+i).text(val);}}
if(!$(".page__block--tracking .card").hasClass('opened'))
$(".page__block--tracking .card").slideToggle("fast",function(){$(this).addClass('opened')});}
if(data.success=="false"){calculator.errorPicker(data.error);}}});},nngPrint:function(ref){$.ajax({type:"GET",url:calculator.url+calculator.api.get.print,dataType:"json",date:{apiKey:calculator.key,ref:ref},success:function(data){if(data.success=="true"){console.log(data);}}});},fillCheck:function(data){for(var key in calculator.calcDataset){if(key=="departureCondition"||key=="deliveryCondition"){serviceCode=calculator.calcDataset[key];serviceName=$('input[value="'+serviceCode+'"]').attr('name');$('#'+key).text(serviceName);}else if($('#'+key).length>0){$('#'+key).text(calculator.calcDataset[key]);}}
for(var key in data[0]){if(key=="addServices"){serviceCode=data[0][key][0]["service"];serviceCost=data[0][key][0]["cost"];serviceName=$('input[value='+serviceCode+']').attr('name');$('#'+key).text(serviceName);$('#addServicesCost').text(serviceCost);}else if($('#'+key).length>0)
{$('#'+key).text(data[0][key]);}}
$('#check, #user_order_fields').show();},userSet:function(){$('#sender input[type=text]').keyup(function(e){var fieldName=$(this).attr('name');var val=$(this).val();calculator.senderUserDataset[fieldName]=val;if($('div.declaration__block--from div.'+fieldName).length>0){$('div.declaration__block--from div.'+fieldName).text(val);}});$('#recipient input[type=text]').keyup(function(e){var fieldName=$(this).attr('name')
var val=$(this).val();calculator.recipientUserDataset[fieldName]=val;if($('div.declaration__block--to div.'+fieldName).length>0){$('div.declaration__block--to div.'+fieldName).text(val);}});},getDepartureConditions:function(){$.ajax({type:"GET",url:calculator.url+calculator.api.get.getDepartureConditions,dataType:"json",success:function(data){if(data.success=="true"){var result=data.data;var html='<select>';for(var i in result){html+='<option value="'+result[i]["ref"]+'">'+result[i]["description"]+'</option>';}
html+='</select>';$('#departureConditions').html(html);$('#departureConditions select').change(function(){var val=$(this).val();calculator.calcDataset.departureCondition=val;});}
if(data.success=="false"){calculator.errorPicker(data.error);}}});},getDeliveryConditions:function(){$.ajax({type:"GET",url:calculator.url+calculator.api.get.getDeliveryConditions,dataType:"json",success:function(data){if(data.success=="true"){var result=data.data;var html='<select>';for(var i in result){html+='<option value="'+result[i]["ref"]+'">'+result[i]["description"]+'</option>';}
html+='</select>';$('#deliveryConditions').html(html);$('#deliveryConditions select').change(function(){var val=$(this).val();calculator.calcDataset.deliveryCondition=val;});}
if(data.success=="false"){calculator.errorPicker(data.error);}}});},getAdditionalServices:function(){$.ajax({type:"GET",url:calculator.url+calculator.api.get.getAdditionalServices,data:{language:calculator.lang},dataType:"json",success:function(data){if(data.success=="true"){var result=data.data;var resArr={};for(var l in result){var services={};for(var k in result){if(result[k]["serviceGroup"]==result[l]["serviceGroup"])
services[k]=result[k];}
resArr[result[l]["serviceGroup"]]=services;}
var html='';for(var i in resArr){var services=resArr[i];html+='<div class="calc-group__content p-y-0">'+'<div data-uk-accordion="{collapse: false}" class="uk-accordion uk-accordion--calc">'+'<h3 class="uk-accordion-title">'+i+'</h3>'+'<div class="uk-accordion-content">'+'<div class="uk-form">'+'<div class="uk-grid uk-grid-width-small-1-1 uk-grid-width-medium-1-1 uk-grid-width-large-1-3 uk-grid-width-xlarge-1-3">';for(var i in services){html+='<div class="uk-form-row">'+'<label class="uk-form-checkbox">'+'<input type="checkbox" name="'+services[i]["serviceGroup"]+'" value="'+services[i]["ref"]+'">'+'<span class="uk-form-checkbox__text">'+services[i]["description"]+'</span>'+'</label>'+'<input type="text" class="count uk-form-width-mini text-xs-center" value="1"/>'+'<span class="uk-form-suffix">шт.</span>'+'</div>';}
html+='</div>'+'</div>'+'</div>'+'</div>'+'</div>';}
$('#services').html(html);calculator.calcDataset.addServices=[];$('#services input').change(function(){var val=$(this).val();var count=$(this).parents('div.uk-form-row').find('input.count').val();calculator.calcDataset.addServices.push({"service":val,"count":count});console.log(calculator.calcDataset.addServices);});}
if(data.success=="false"){calculator.errorPicker(data.error);}}});},reverseAB:function(){$('.calc-group__toggle').click(function(){var tmpDep=calculator.calcDataset.rspSender;calculator.calcDataset.rspSender=calculator.calcDataset.rspRecipient;calculator.calcDataset.rspRecipient=tmpDep;var tmpCity=calculator.recipientUserDataset.town;calculator.recipientUserDataset.town=calculator.senderUserDataset.town;calculator.senderUserDataset.town=tmpCity;var checkFrom=$('#check .city_from').text();var checkTo=$('#check .city_to').text();$('#check .city_to').text(checkFrom);$('#check .city_from').text(checkTo);var from=$('.calc_city_from.tt-input').val();var to=$('.calc_city_to.tt-input').val();$('.calc_city_from').typeahead('val',to);$('.calc_city_to').typeahead('val',from);return false;});},acivateCityPoint:function(){$('.calc_city_point').eq(1).addClass('active');$('.calc_city_point').click(function(){$('.calc_city_point').removeClass('active');$(this).addClass('active');})},otherParams:function(){calculator.calcDataset.weight=$('input[name="weight"]').val();calculator.calcDataset.declaredCost=$('input[name="declaredCost"]').val();calculator.calcDataset.volumeGeneral=$('input[name="volumeGeneral"]').val();$('input[name="weight"]').keypress(function(e){if(!calculator.isNumberKey(e))
return false;}).keyup(function(){var val=$(this).val();calculator.calcDataset.weight=val;});$('input[name="declaredCost"]').keypress(function(e){if(!calculator.isNumberKey(e))
return false;}).keyup(function(){var val=$(this).val();calculator.calcDataset.declaredCost=val;});$('input[name="volumeGeneral"]').keypress(function(e){if(!calculator.isNumberKey(e))
return false;}).keyup(function(){var val=$(this).val();calculator.calcDataset.volumeGeneral=val;});},cubeParams:function(){if($('#cube_input_length').val()!=""){calculator.calcDataset.length=$('#cube_input_length').val()}
if($('#cube_input_width').val()!=""){calculator.calcDataset.width=$('#cube_input_width').val()}
if($('#cube_input_height').val()!=""){calculator.calcDataset.height=$('#cube_input_height').val()}
$('#cube_slider_length').on('change',function(e){if(e.value!==undefined)
calculator.calcDataset.length=e.value.newValue;});$('#cube_slider_width').on('change',function(e){if(e.value!==undefined)
calculator.calcDataset.width=e.value.newValue;});$('#cube_slider_height').on('change',function(e){if(e.value!==undefined)
calculator.calcDataset.height=e.value.newValue;});},initCalendar:function(){$(".timer").flatpickr({enableTime:true,noCalendar:true,});$(".calendar").flatpickr({"locale":calculator.lang,enableTime:false,dateFormat:"d-m-Y",altFormat:"j.m.Y h:i K",clickOpens:false,wrap:true,minDate:new Date(),onChange:function(selectedDates,dateStr,instance){if($(instance.element).hasClass('from')===true){calculator.nngDataset.date=dateStr;$('div.declaration__block--from div.date span').text(dateStr);}
if($(instance.element).hasClass('to')===true){$('div.declaration__block--to div.date span').text(dateStr);}}});},place:function(){if($('ul.place_from .door').hasClass('active')){calculator.calcDataset.departure=true;$('#check .i').text($('.place_from li.door span').text());}else{calculator.calcDataset.departure=false;$('#check .point_from').text($('.place_from li.department span').text());$('.wrapDepartureConditions, .timeFrom').hide();}
if($('ul.place_to .door').hasClass('active')){calculator.calcDataset.delivery=true;$('#check .point_to').text($('.place_to li.door span').text());}else{calculator.calcDataset.delivery=false;$('#check .point_to').text($('.place_to li.department span').text());$('.wrapDeliveryConditions, .timeTo').hide();}
$('ul.place_from li').click(function(){$(this).parent().find('li.active').removeClass('active');$(this).addClass('active');if($(this).hasClass('door')){calculator.calcDataset.departure=true;$('#check .point_from').text($('.place_from li.door span').text());$('.wrapDepartureConditions, .timeFrom').show();}else if(calculator.calcDataset.departure!==undefined){calculator.calcDataset.departure=false;$('#check .point_from').text($('.place_from li.department span').text());$('.wrapDepartureConditions, .timeFrom').hide();}
return false;});$('ul.place_to li').click(function(){$(this).parent().find('li.active').removeClass('active');$(this).addClass('active');if($(this).hasClass('door')){calculator.calcDataset.delivery=true;$('#check .point_to').text($('.place_to li.door span').text());$('.wrapDeliveryConditions, .timeTo').show();}else if(calculator.calcDataset.delivery!==undefined){calculator.calcDataset.delivery=false;$('#check .point_to').text($('.place_to li.department span').text());$('.wrapDeliveryConditions, .timeTo').hide();}
return false;});},initCargoType:function(){$.ajax({type:"GET",url:calculator.url+calculator.api.get.getCargoTypes,dataType:"json",success:function(data){if(data.success=="true"){var cargoTypes=[];for(var i in data.data){var item=data.data[i];if(cargoTypes[item.type]==undefined)
cargoTypes[item.type]=[];cargoTypes[item.type].push(item);}
self.cargoTypes=cargoTypes;for(var i in cargoTypes)
{$('select#cargoTypes').append('<option>'+i+'</option>');}
$('select#cargoTypes').trigger('change');}
if(data.success=="false"){calculator.errorPicker(data.error);}}});$('select#cargoTypes').change(function(){if($(this).val()!='')
{var cargo=self.cargoTypes[$(this).val()];$('select#cargoTypesSub').html('');for(var i in cargo)
{$('select#cargoTypesSub').append('<option value="'+cargo[i].ref+'">'+cargo[i].description+'</option>');}
firstOption=$('select#cargoTypesSub option:first');firstOption.attr('selected','selected');$('select#cargoTypesSub').parent().find('span').html(firstOption.text());calculator.calcDataset.cargoType=firstOption.val();}});$(document).on('change','select#cargoTypesSub',function(){calculator.calcDataset.cargoType=$(this).val();});},setDepartment:function(departmentInfo){$('.calc_city_point.active').typeahead('val',departmentInfo.description+', '+departmentInfo.address);if($('.calc_city_from.active').length>0){calculator.calcDataset.rspSender=departmentInfo.ref;calculator.calcDataset.townSender=departmentInfo.cityRef;calculator.senderUserDataset.town=departmentInfo.cityref;$('#check .city_from').text(departmentInfo.description);$('#sender input[name=address]').val(departmentInfo.address)}
if($('.calc_city_to.active').length>0){calculator.calcDataset.rspRecipient=departmentInfo.ref;calculator.calcDataset.townRecipient=departmentInfo.cityRef;calculator.recipientUserDataset.town=departmentInfo.cityref;$('#check .city_to').text(departmentInfo.description);$('#recipient input[name=address]').val(departmentInfo.address)}},isNumberKey:function(evt){var charCode=(evt.which)?evt.which:event.keyCode
if(charCode>31&&(charCode<48||charCode>57))
return false;return true;},searchCity:function(){var self=this;var SearchCity=function(){return function findMatches(q,cb,async){var params={"searchstring":q,};var queryUrl;if(self.point=="from"&&calculator.calcDataset.departure==false){queryUrl=calculator.url+calculator.api.get.getRsp}
if(self.point=="from"&&calculator.calcDataset.departure==true){queryUrl=calculator.url+calculator.api.get.getTowns}
if(self.point=="to"&&calculator.calcDataset.delivery==false){queryUrl=calculator.url+calculator.api.get.getRsp}
if(self.point=="to"&&calculator.calcDataset.delivery==true){queryUrl=calculator.url+calculator.api.get.getTowns}
$.ajax({url:queryUrl,data:params,type:"GET",dataType:"json"}).done(function(data){var matches=[];if(data.success=="true"){for(var key in data.data){matches.push(data.data[key]);}
async(matches);}
else
{var error={'description':data.error.text};matches.push(error);async(matches);}}).fail(function(){alert("error");});};};var typeahead=$('.calc_city_point').typeahead({hint:true,highlight:true,minLength:3,async:true},{name:'states',displayKey:'description',source:SearchCity(),templates:{empty:'Ничего не найдено...',suggestion:function(data){return'<div>'+data.description+'</div>'},pending:function(data){return'<div>Поиск..</div>'}}}).on('typeahead:active',function(e){if($(e.target).hasClass('calc_city_from')===true){self.point="from";}
if($(e.target).hasClass('calc_city_to')===true){self.point="to";}}).on('typeahead:selected',function(event,data){if(self.point=="from"&&calculator.calcDataset.departure==false){calculator.calcDataset.townSender=data.cityRef;calculator.senderUserDataset.town=data.cityRef;calculator.calcDataset.rspSender=data.ref;$('#sender input[name=address]').val(data.address);}
if(self.point=="from"&&calculator.calcDataset.departure==true){calculator.calcDataset.townSender=data.ref;calculator.senderUserDataset.town=data.ref;calculator.calcDataset.rspSender=data.rspRef;$('#sender input[name=address]').val('');}
if(self.point=="to"&&calculator.calcDataset.delivery==false){calculator.calcDataset.townRecipient=data.cityRef;calculator.recipientUserDataset.town=data.cityRef;calculator.calcDataset.rspRecipient=data.ref;$('#recipient input[name=address]').val(data.address);}
if(self.point=="to"&&calculator.calcDataset.delivery==true){calculator.calcDataset.townRecipient=data.ref;calculator.recipientUserDataset.town=data.ref;calculator.calcDataset.rspRecipient=data.rspRef;$('#recipient input[name=address]').val('');}});},calculate:function(){console.log(calculator.calcDataset);var params=JSON.stringify(calculator.calcDataset);$.ajax({type:"POST",url:calculator.url+calculator.api.post.calc,data:params,success:function(data){var result=JSON.parse(data);console.log(result);if(result.success=="true"){console.log(result.data);calculator.fillCheck(result.data);}
if(data.success=="false"){calculator.errorPicker(data.error);}}});}}
$(document).ready(function(){calculator.init({mode:'openws',lang:'ru',api:{study:{key:'8c236ec1-6e15-424b-8daf-33913831',url:'http://urm.sat.ua/study/hs/api/v1.0/',},openws:{key:'8c236ec1-6e15-424b-8daf-33913831',url:'http://urm.sat.ua/openws/hs/api/v1.0/',},get:{recipentList:'catalogs/Counterparty/json/list',printNng:'documents/nng/json/print',tracking:'tracking/json',counterparty:'catalogs/Counterparty/json/list',getRsp:'main/json/getRsp',nngList:'documents/nng/json/list',getCargoTypes:'main/json/getCargoTypes',getTowns:'main/json/getTowns',getDepartureConditions:'main/json/getDepartureConditions',getDeliveryConditions:'main/json/getDeliveryConditions',getAdditionalServices:'main/json/getAdditionalServices',},post:{calc:'calc/json',createUser:'catalogs/Counterparty/json/save',createDocNng:"documents/nng/json/save",}}});});